### ISSUE TITLE
Cannot require with node 10

### ISSUE THREAD

**Issue by pimterry** [natevw/fatfs#27]
Using node 10 & fatfs 0.10.6 (latest):

```
> require('fatfs')
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:53:11)
    at Buffer.readUInt32BE (internal/buffer.js:198:5)
```

**Comment by natevw** [comment]
So I've published struct-fu@1.2.1 which should fix this via your pull request for the upstream issue refrenced.

However in a quick test:

```
mkdir tmp && cd tmp
npm install fatfs
npm list
```

Is still showing it install `struct-fu@1.2.0`. Likewise although `npm publish` on the struct-fu repo now shows "You cannot publish over the previously published versions: 1.2.1. : struct-fu" the most recent version listed at https://www.npmjs.com/package/struct-fu is still 1.2.0.

I'm going to assume this is a caching issue on the npm side which will clear up soon, but if not please don't hesitate to poke me and I'll do some more investigating!

**Comment by pimterry** [comment]
Sure, will do. Npm issues definitely sound plausible. Thanks for your help with this! And for all your work on fatfs itself of course :+1:

**Comment by natevw** [comment]
Looks like npm is now installing struct-fu@1.2.1 alongside fatfs, so I think you should be good to go! Thanks for helping maintain this.
